const questionsData = {
  default: [
    {
      id: 1,
      text: 'Quelle est la capitale de la France ?',
      options: ['Paris', 'Berlin', 'Londres', 'Madrid'],
      correctAnswer: 'Paris',
    },   
    {
      id: 2,
      text: 'Quelle est la plus grande planète du système solaire ?',
      options: ['Terre', 'Jupiter', 'Mars', 'Vénus'],
      correctAnswer: 'Jupiter',
    },
    {
      id: 3,
      text: 'Quel langage de programmation est utilisé pour développer des applications Android ?',
      options: ['Java', 'Python', 'C#', 'Swift'],
      correctAnswer: 'Java',
    },
    {
      id: 4,
      text: 'Quelle est la capitale du Japon ?',
      options: ['Séoul', 'Pékin', 'Tokyo', 'Bangkok'],
      correctAnswer: 'Tokyo',
    },
    {
      id: 5,
      text: 'Quel est le plus grand océan du monde ?',
      options: ['Océan Atlantique', 'Océan Indien', 'Océan Arctique', 'Océan Pacifique'],
      correctAnswer: 'Océan Pacifique',
    },
    {
      id: 6,
      text: 'Quel est le langage de balisage utilisé pour créer des pages web ?',
      options: ['HTML', 'CSS', 'JavaScript', 'Python'],
      correctAnswer: 'HTML',
    },
    {
      id: 7,
      text: 'Quel pays est le plus grand en superficie ?',
      options: ['Russie', 'Canada', 'États-Unis', 'Chine'],
      correctAnswer: 'Russie',
    },
    {
      id: 8,
      text: 'Quel compositeur autrichien est célèbre pour ses symphonies et opéras classiques ?',
      options: ['Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Johann Sebastian Bach', 'Pyotr Ilyich Tchaikovsky'],
      correctAnswer: 'Wolfgang Amadeus Mozart',
    },
    {
      id: 9,
      text: 'Quel est le plus haut sommet du monde ?',
      options: ['Mont Everest', 'K2', 'Kangchenjunga', 'Lhotse'],
      correctAnswer: 'Mont Everest',
    },
    {
      id: 10,
      text: 'Quel est le plus long fleuve du monde ?',
      options: ['Nil', 'Amazonie', 'Mississippi', 'Yangtsé'],
      correctAnswer: 'Nil',
    },
  ],
  history: [
    {
      id: 1,
      text: 'En quelle année a eu lieu la Révolution française ?',
      options: ['1789', '1799', '1801', '1776'],
      correctAnswer: '1789',
    },
    {
      id: 2,
      text: 'Quel empereur romain a construit le Colisée à Rome ?',
      options: ['Auguste', 'Néron', 'Vespasien', 'Trajan'],
      correctAnswer: 'Vespasien',
    },
    {
      id: 3,
      text: 'Quel événement a marqué le début de la Première Guerre mondiale en 1914 ?',
      options: ['L\'assassinat de l\'archiduc François-Ferdinand', 'La bataille de la Somme', 'La révolution russe', 'Le traité de Versailles'],
      correctAnswer: "L'assassinat de l'archiduc François-Ferdinand",
    },
    {
      id: 4,
      text: 'Quel événement a marqué la fin de la Seconde Guerre mondiale en 1945 ?',
      options: ['La bataille de Stalingrad', 'Le débarquement en Normandie', 'La bombe atomique sur Hiroshima', 'La conférence de Yalta'],
      correctAnswer: 'La bombe atomique sur Hiroshima',
    },
    {
      id: 5,
      text: 'Quelle reine a régné sur l\'Angleterre au XIXe siècle pendant l\'ère victorienne ?',
      options: ['Reine Marie-Antoinette', 'Reine Victoria', 'Reine Élisabeth I', 'Reine Catherine la Grande'],
      correctAnswer: 'Reine Victoria',
    },
    {
      id: 6,
      text: 'Quel explorateur a réalisé le premier tour du monde au XVIe siècle ?',
      options: ['Christophe Colomb', 'Ferdinand Magellan', 'Marco Polo', 'James Cook'],
      correctAnswer: 'Ferdinand Magellan',
    },
    {
      id: 7,
      text: 'Quelle dynastie a régné sur la Chine pendant la majeure partie de la période impériale chinoise ?',
      options: ['Han', 'Tang', 'Ming', 'Qing'],
      correctAnswer: 'Qing',
    },
    {
      id: 8,
      text: 'Quel leader politique sud-africain a joué un rôle clé dans l\'abolition de l\'apartheid et est devenu le premier président noir de l\'Afrique du Sud ?',
      options: ['Nelson Mandela', 'Thabo Mbeki', 'Frederik de Klerk', 'Desmond Tutu'],
      correctAnswer: 'Nelson Mandela',
    },
    {
      id: 9,
      text: 'Quelle guerre a été déclenchée par l\'attaque surprise de Pearl Harbor en 1941 ?',
      options: ['Guerre du Golfe', 'Guerre du Vietnam', 'Seconde Guerre mondiale', 'Guerre froide'],
      correctAnswer: 'Seconde Guerre mondiale',
    },
    {
      id: 10,
      text: 'Quelle reine d\'Égypte est célèbre pour sa liaison avec Marc Antoine et Jules César ?',
      options: ['Cleopâtre', 'Néfertiti', 'Hatshepsout', 'Isis'],
      correctAnswer: 'Cleopâtre',
    },
    // Ajoutez d'autres questions pour le thème "history" si nécessaire
  ],
  science: [
    {
      id: 1,
      text: 'Quelle est la formule chimique de l\'eau ?',
      options: ['H2O', 'CO2', 'O2', 'CH4'],
      correctAnswer: 'H2O',
    },{
      id: 2,
      text: 'Quel physicien a formulé la théorie de la relativité restreinte ?',
      options: ['Isaac Newton', 'Albert Einstein', 'Galilée', 'Niels Bohr'],
      correctAnswer: 'Albert Einstein',
    },
    {
      id: 3,
      text: 'Quel élément chimique a le symbole "O" dans le tableau périodique ?',
      options: ['Oxygène', 'Or', 'Azote', 'Argent'],
      correctAnswer: 'Oxygène',
    },
    {
      id: 4,
      text: 'Quel scientifique a formulé les lois du mouvement et la loi de la gravitation universelle ?',
      options: ['Isaac Newton', 'Galilée', 'Copernic', 'Kepler'],
      correctAnswer: 'Isaac Newton',
    },
    {
      id: 5,
      text: 'Quelle est la plus petite particule d\'un élément chimique ?',
      options: ['Atome', 'Molécule', 'Proton', 'Électron'],
      correctAnswer: 'Électron',
    },
    {
      id: 6,
      text: 'Qui a découvert la pénicilline, le premier antibiotique ?',
      options: ['Louis Pasteur', 'Alexander Fleming', 'Marie Curie', 'Antoine Lavoisier'],
      correctAnswer: 'Alexander Fleming',
    },
    {
      id: 7,
      text: 'Quel élément chimique a le numéro atomique 79 ?',
      options: ['Or', 'Argent', 'Cuivre', 'Platine'],
      correctAnswer: 'Or',
    },
    {
      id: 8,
      text: 'Quelle planète est souvent appelée la "planète rouge" en raison de sa couleur ?',
      options: ['Vénus', 'Mars', 'Jupiter', 'Saturne'],
      correctAnswer: 'Mars',
    },
    {
      id: 9,
      text: 'Quel scientifique a développé la théorie de l\'évolution par sélection naturelle ?',
      options: ['Isaac Newton', 'Charles Darwin', 'Gregor Mendel', 'Louis Pasteur'],
      correctAnswer: 'Charles Darwin',
    },
    {
      id: 10,
      text: 'Quelle est la couche la plus externe de la Terre sur laquelle nous vivons ?',
      options: ['Manteau', 'Croûte', 'Noyau externe', 'Asthenosphère'],
      correctAnswer: 'Croûte',
    },
    // Ajoutez d'autres questions pour le thème "science" si nécessaire
  ],
  sport: [
    {
      id: 1,
      text: 'Quelle équipe a remporté la Coupe du Monde de football en 2018 ?',
      options: ['France', 'Brésil', 'Allemagne', 'Espagne'],
      correctAnswer: 'France',
    },
    {
      id: 2,
      text: 'Qui est le recordman du monde du saut en hauteur en athlétisme ?',
      options: ['Sergei Bubka', 'Usain Bolt', 'Javier Sotomayor', 'Renaud Lavillenie'],
      correctAnswer: 'Javier Sotomayor',
    },
    {
      id: 3,
      text: 'Quel joueur de basketball est surnommé "The King" ?',
      options: ['Stephen Curry', 'LeBron James', 'Kevin Durant', 'Kobe Bryant'],
      correctAnswer: 'LeBron James',
    },
    {
      id: 4,
      text: 'Dans quel sport la Ryder Cup est-elle disputée ?',
      options: ['Golf', 'Tennis', 'Cricket', 'Rugby'],
      correctAnswer: 'Golf',
    },
    {
      id: 5,
      text: 'Quelle nation a remporté le plus grand nombre de médailles d\'or aux Jeux Olympiques d\'été 2016 ?',
      options: ['États-Unis', 'Chine', 'Russie', 'Royaume-Uni'],
      correctAnswer: 'États-Unis',
    },
    {
      id: 6,
      text: 'Quel est le plus grand tournoi de tennis de la saison sur gazon ?',
      options: ['Open d\'Australie', 'Roland Garros', 'Wimbledon', 'US Open'],
      correctAnswer: 'Wimbledon',
    },
    {
      id: 7,
      text: 'Combien de joueurs composent une équipe de football sur le terrain lors d\'un match régulier ?',
      options: ['9', '10', '11', '12'],
      correctAnswer: '11',
    },
    {
      id: 8,
      text: 'Quel pays a remporté le plus grand nombre de médailles d\'or aux Jeux Olympiques d\'hiver 2018 ?',
      options: ['Norvège', 'Allemagne', 'Canada', 'États-Unis'],
      correctAnswer: 'Norvège',
    },
    {
      id: 9,
      text: 'Qui est le meilleur buteur de l\'histoire de la Ligue des champions de l\'UEFA ?',
      options: ['Lionel Messi', 'Cristiano Ronaldo', 'Raul', 'Robert Lewandowski'],
      correctAnswer: 'Cristiano Ronaldo',
    },
    {
      id: 10,
      text: 'Quelle équipe a remporté le plus grand nombre de Super Bowls dans l\'histoire de la NFL ?',
      options: ['New England Patriots', 'Dallas Cowboys', 'Pittsburgh Steelers', 'San Francisco 49ers'],
      correctAnswer: 'New England Patriots',
    },
  ],
  videoGame: [
    {
      id: 1,
      text: 'Quel jeu vidéo a été le premier à être commercialisé en 1972 ?',
      options: ['Pong', 'Space Invaders', 'Pac-Man', 'Donkey Kong'],
      correctAnswer: 'Pong',
    },
    {
      id: 2,
      text: 'Quelle franchise de jeux vidéo met en scène un plombier appelé Mario ?',
      options: ['Sonic the Hedgehog', 'The Legend of Zelda', 'Super Mario', 'Final Fantasy'],
      correctAnswer: 'Super Mario',
    },
    {
      id: 3,
      text: 'Qui est le créateur emblématique de la série de jeux vidéo "Metal Gear Solid" ?',
      options: ['Hideo Kojima', 'Shigeru Miyamoto', 'Satoru Iwata', 'Koji Igarashi'],
      correctAnswer: 'Hideo Kojima',
    },
    {
      id: 4,
      text: 'Quel est le jeu vidéo le plus vendu de tous les temps ?',
      options: ['Minecraft', 'Tetris', 'Grand Theft Auto V', 'Super Mario Bros.'],
      correctAnswer: 'Minecraft',
    },
    {
      id: 5,
      text: 'Quelle console de jeux vidéo a été lancée par Sony en 1994 ?',
      options: ['Nintendo 64', 'PlayStation', 'Sega Saturn', 'Xbox'],
      correctAnswer: 'PlayStation',
    },
    {
      id: 6,
      text: 'Dans quel jeu vidéo le personnage principal s\'appelle Link et doit sauver la princesse Zelda ?',
      options: ['Super Mario Bros.', 'The Legend of Zelda', 'Final Fantasy VII', 'Dark Souls'],
      correctAnswer: 'The Legend of Zelda',
    },
    {
      id: 7,
      text: 'Quelle franchise de jeux vidéo est connue pour ses combats entre robots géants appelés "Mobile Suits" ?',
      options: ['Final Fantasy', 'Gundam', 'Mega Man', 'Street Fighter'],
      correctAnswer: 'Gundam',
    },
    {
      id: 8,
      text: 'Quel jeu vidéo a popularisé le genre battle royale avec son mode "Fortnite Battle Royale" ?',
      options: ['PlayerUnknown\'s Battlegrounds (PUBG)', 'Apex Legends', 'Fortnite', 'Call of Duty: Warzone'],
      correctAnswer: 'Fortnite',
    },
    {
      id: 9,
      text: 'Quelle série de jeux vidéo a pour protagoniste le chasseur de monstres professionnel Geralt de Riv ?',
      options: ['Dark Souls', 'The Elder Scrolls', 'Monster Hunter', 'The Witcher'],
      correctAnswer: 'The Witcher',
    },
    {
      id: 10,
      text: 'Quel jeu vidéo a introduit le personnage emblématique Lara Croft, une archéologue aventurière ?',
      options: ['Uncharted', 'Tomb Raider', 'Assassin\'s Creed', 'Prince of Persia'],
      correctAnswer: 'Tomb Raider',
    },
  ],
  cinema: [
    {
      id: 1,
      text: 'Quel film a remporté l\'Oscar du meilleur film en 2020 ?',
      options: ['1917', 'Joker', 'Parasite', 'Once Upon a Time in Hollywood'],
      correctAnswer: 'Parasite',
    },
    {
      id: 2,
      text: 'Quel réalisateur est connu pour des films tels que "Pulp Fiction" et "Kill Bill" ?',
      options: ['Christopher Nolan', 'Quentin Tarantino', 'Martin Scorsese', 'Steven Spielberg'],
      correctAnswer: 'Quentin Tarantino',
    },
    {
      id: 3,
      text: 'Quelle actrice a remporté l\'Oscar de la meilleure actrice pour son rôle dans "La La Land" ?',
      options: ['Meryl Streep', 'Natalie Portman', 'Emma Stone', 'Cate Blanchett'],
      correctAnswer: 'Emma Stone',
    },
    {
      id: 4,
      text: 'Quel film d\'animation met en scène des jouets qui prennent vie lorsque les humains ne sont pas présents ?',
      options: ['Shrek', 'Toy Story', 'Finding Nemo', 'Frozen'],
      correctAnswer: 'Toy Story',
    },
    {
      id: 5,
      text: 'Qui a réalisé le film "Inception" sorti en 2010 ?',
      options: ['David Fincher', 'Christopher Nolan', 'Quentin Tarantino', 'Alfonso Cuarón'],
      correctAnswer: 'Christopher Nolan',
    },
    {
      id: 6,
      text: 'Quel film a introduit le personnage de Jack Dawson et a remporté 11 Oscars en 1998 ?',
      options: ['Titanic', 'Avatar', 'The Godfather', 'Forrest Gump'],
      correctAnswer: 'Titanic',
    },
    {
      id: 7,
      text: 'Quel acteur a interprété le personnage de Neo dans la trilogie "The Matrix" ?',
      options: ['Keanu Reeves', 'Tom Cruise', 'Brad Pitt', 'Leonardo DiCaprio'],
      correctAnswer: 'Keanu Reeves',
    },
    {
      id: 8,
      text: 'Quel film a remporté le premier Oscar du meilleur film en 1929 ?',
      options: ['Gone with the Wind', 'Casablanca', 'The Godfather', 'Wings'],
      correctAnswer: 'Wings',
    },
    {
      id: 9,
      text: 'Quel réalisateur français est connu pour ses films tels que "Amélie Poulain" et "The Da Vinci Code" ?',
      options: ['Luc Besson', 'François Truffaut', 'Jean-Luc Godard', 'Ron Howard'],
      correctAnswer: 'Jean-Pierre Jeunet',
    },
    {
      id: 10,
      text: 'Quel film a remporté l\'Oscar du meilleur film en 1994 et est basé sur un roman de Stephen King ?',
      options: ['Forrest Gump', 'Pulp Fiction', 'The Shawshank Redemption', 'Schindler\'s List'],
      correctAnswer: 'The Shawshank Redemption',
    },
  ],
  // ... ajoutez d'autres thèmes si nécessaire
};

export default questionsData;